name: Run Chaos Experiments
on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  run-experiments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Setup python virtual env
        run: |
          pip install -U chaostoolkit
          pip install -U chaostoolkit-spring

      - name: Run application experiments
        run: chaos run ./experiments/application-experiment.json

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create log and journal buckets
        run: |
          aws s3api create-bucket --bucket chaostoolkit-log-bucket
          aws s3api create-bucket --bucket chaostoolkit-journal-bucket

      - name: Move logs and journal to s3
        run: |
          aws s3 cp ./chaostoolkit.log s3://chaostoolkit-log-bucket/${{ steps.date.outputs.date }}-chaostoolkit.log
          aws s3 cp ./journal.json s3://chaostoolkit-journal-bucket/${{ steps.date.outputs.date }}-journal.json