on:
  release:
    types: [created]

name: Deploy Springboot application

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - uses: actions/upload-artifact@v2
        with:
         name: java-build-artifact
         path: target/**.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.CDK_DEFAULT_REGION }}

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
          cache-dependency-path: infra/aws/package-lock.json

      - name: Copying java build artifact
        uses: actions/download-artifact@v2
        with:
          name: java-build-artifact
          path: target

      - name: Deploy Cloudfront on AWS
        run: |
          cd infra/aws && npm ci
          npm run cdk -- bootstrap
          npm run cdk -- deploy --require-approval never